/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 *
 * @author pawelidziak
 */
public class AddressBookBean extends javax.swing.JPanel {

    /**
     * Creates new form AddressBookBean
     */
    public AddressBookBean() {
        initComponents();
        defaultListModel = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        title = new JLabel();
        jLabel1 = new JLabel();
        b_remove = new javax.swing.JButton();
        b_add = new javax.swing.JButton();
        tf_name = new javax.swing.JTextField();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        tf_surname = new javax.swing.JTextField();
        jLabel4 = new JLabel();
        tf_email = new javax.swing.JTextField();
        jLabel5 = new JLabel();
        tf_filter = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new JLabel();
        filter = new JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        title.setText("Title");

        jLabel1.setText("List of records:");

        b_remove.setText("Remove");
        b_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_removeActionPerformed(evt);
            }
        });

        b_add.setText("Add");
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addActionPerformed(evt);
            }
        });

        jLabel2.setText("Name:");

        jLabel3.setText("Surname:");

        jLabel4.setText("Email:");

        jLabel5.setText("Set filter:");

        jButton1.setText("Apply filter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Current filter:");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(tf_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel2)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel5)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(tf_filter))
                                                                        .addComponent(b_remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(jLabel6)
                                                                                .addGap(98, 98, 98))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(101, 101, 101)
                                                                .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(88, 88, 88))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(b_add, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(178, 178, 178)
                                                                .addComponent(title))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(141, 141, 141)
                                                                .addComponent(jLabel1))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel3)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(title)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel4)
                                                        .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(b_remove)
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(tf_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14)
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(tf_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(b_add)
                                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>

    // ADD RECORD
    private void b_addActionPerformed(java.awt.event.ActionEvent evt) {
        String name = tf_name.getText();
        String surname = tf_surname.getText();
        String email = tf_email.getText();
        addRecord(name, surname, email);
    }

    // SET FILTER
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String newFilter = tf_filter.getText();
        setNewFilter(newFilter);
    }

    // REMOVE RECORD
    private void b_removeActionPerformed(java.awt.event.ActionEvent evt) {
        int index = jList1.getSelectedIndex();
        if (index == -1) {
            return;
        }
        removeRecord(index);
    }


    // Variables declaration - do not modify
    private javax.swing.JButton b_add;
    private javax.swing.JButton b_remove;
    private JLabel filter;
    private javax.swing.JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private javax.swing.JList<AddressBookRecord> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_filter;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_surname;
    private JLabel title;
    // End of variables declaration

    private DefaultListModel<AddressBookRecord> defaultListModel;
    private int maxRowsNumber = 10;

    // METODY PUBLICZNE
    public void setTitle(String title) {
        this.title.setText(title);
    }

    public String getTitle() {
        return title.getText();
    }

    public String getFilter() {
        return filter.getText();
    }

    public void setFilter(String filter) {
        this.filter.setText(filter);
    }

    public void setMaxRows(int maxRowsNumber){
        this.maxRowsNumber = maxRowsNumber;
        for(int i = maxRowsNumber; i <defaultListModel.size(); i++){
            defaultListModel.remove(i);
        }
    }
    public int getMaxRows(){
        return maxRowsNumber;
    }

    // METODY PRYWATNE
    private void addRecord(String name, String surname, String email) {
        System.out.println(defaultListModel.size());
        if (defaultListModel.size() == maxRowsNumber) {
            return;
        }
        if (name == null || name.isEmpty() || surname == null || surname.isEmpty() || email == null || email.isEmpty()) {
            return;
        }
        if (getFilter() != null && !getFilter().isEmpty() && email.contains(getFilter())) {
            return;
        }
        defaultListModel.addElement(new AddressBookRecord(name, surname, email));
        jList1.setModel(defaultListModel);
    }

    // REMOVE RECORD
    private void removeRecord(int index){
        defaultListModel.remove(index);
    }

    // SET NEW FILTER
    private void setNewFilter(String filter){
        if (filter == null || filter.isEmpty()) {
            System.out.println("Filter cannot be null or empty.");
            return;
        }

        for (int i = 0; i < defaultListModel.getSize(); i++) {
            if (defaultListModel.get(i).getEmail().contains(filter)) {
                System.out.println("Some records matching this filter are already in AddressBook, remove them before applying this filter.");
                return;
            }
        }
        setFilter(filter);
    }

    class AddressBookRecord {

        private String name;
        private String surname;
        private String email;

        public AddressBookRecord(String name, String surname, String email) {
            this.name = name;
            this.surname = surname;
            this.email = email;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getSurname() {
            return surname;
        }

        public void setSurname(String surname) {
            this.surname = surname;
        }

        public String getEmail() {
            return email;
        }

        public void setEmail(String email) {
            this.email = email;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }

            AddressBookRecord that = (AddressBookRecord) o;

            if (name != null ? !name.equals(that.name) : that.name != null) {
                return false;
            }
            if (surname != null ? !surname.equals(that.surname) : that.surname != null) {
                return false;
            }
            return email != null ? email.equals(that.email) : that.email == null;
        }

        @Override
        public int hashCode() {
            int result = name != null ? name.hashCode() : 0;
            result = 31 * result + (surname != null ? surname.hashCode() : 0);
            result = 31 * result + (email != null ? email.hashCode() : 0);
            return result;
        }

        @Override
        public String toString() {
            return "Name: " + name + ", Surname: " + surname + ", Email: " + email;
        }
    }

}
